name: ci

on: push

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: x64
      - name: Install dependencies
        run: |
          pip install pytest

      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v8.0.0
        with:
          coverageCommand: pytest --cov-report xml:coverage.xml --cov=.
          coverageLocations: ${{github.workspace}}/coverage.xml:coverage.py
        env:
          CC_TEST_REPORTER_ID: 71f0aeaa5a493d61a1b8f8bb2e94a4b842e7e75fce1cb4e2a7dac4ad2b1aaf6e
          PYTHONPATH: ${{github.workspace}}/ch08/pytest
