name: inputs_test

on:
  workflow_dispatch:
    inputs:
      lambda_password:
        required: false
        type: string
        default: ''
        description: 'Optional password for Lambda - will be generated if empty'
      dbt_cloud_password:
        required: false
        type: string
        default: ''
        description: 'Optional password for DBT Cloud - will be generated if empty'

env:
    INPUT_LAMBDA_PASSWORD: ${{ inputs.lambda_password }}
    INPUT_DBT_CLOUD_PASSWORD: ${{ inputs.dbt_cloud_password }}

jobs:
  test:
    runs-on: ubuntu-latest
    # Set all inputs as job-level environment variables
    # This prevents them from appearing in command logs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Process passwords
        id: set-passwords
        run: |
          # For Lambda password
          if [ -z "$INPUT_LAMBDA_PASSWORD" ]; then
            # Generate a password if none provided
            LAMBDA_PASSWORD=$(openssl rand -base64 32 | tr -dc 'a-zA-Z0-9' | head -c 32)
          else
            # Use provided password (from env var, not visible in command)
            LAMBDA_PASSWORD="$INPUT_LAMBDA_PASSWORD"
          fi

          # Mask the password
          echo "::add-mask::$LAMBDA_PASSWORD"
          echo "aws_lambda_api_password=$LAMBDA_PASSWORD" >> $GITHUB_OUTPUT

          # For DBT Cloud password
          if [ -z "$INPUT_DBT_CLOUD_PASSWORD" ]; then
            # Generate a password if none provided
            DBT_PASSWORD=$(openssl rand -base64 32 | tr -dc 'a-zA-Z0-9' | head -c 10)
          else
            # Use provided password (from env var, not visible in command)
            DBT_PASSWORD="$INPUT_DBT_CLOUD_PASSWORD"
          fi

          # Mask the password
          echo "::add-mask::$DBT_PASSWORD"
          echo "dbt_cloud_password=$DBT_PASSWORD" >> $GITHUB_OUTPUT

          echo "Passwords have been processed"

      # Example of how to use the passwords in subsequent steps
      - name: Use passwords
        env:
          LAMBDA_PW: ${{ steps.set-passwords.outputs.aws_lambda_api_password }}
          DBT_PW: ${{ steps.set-passwords.outputs.dbt_cloud_password }}
        run: |
          echo "Using masked passwords in this step"
          # Your commands that use the passwords
